# Development compose with hot reload
version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: laune_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend runs on host for faster development
  # Use: cd backend && cargo run

  # Frontend runs on host for faster development
  # Use: cd frontend && pnpm dev

volumes:
  postgres_data:
