name: Bug Report
description: File a bug report to help us improve Laune
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported yet
          required: true
        - label: I have reproduced this issue with the latest version of Laune
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Laune are you running?
      placeholder: "e.g., v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running Laune in?
      options:
        - Development (local)
        - Production (deployed)
        - Docker
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or console output
      placeholder: Paste any relevant error logs here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Backend (Rust API)
        - Frontend (React UI)
        - Database
        - Feed Fetching
        - Summarization
        - Other (please specify in description)

  - type: dropdown
    id: browser
    attributes:
      label: Browser (for frontend issues)
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in description)
        - Not applicable (backend issue)

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
